import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/providers/provider";

export const metadata: Metadata = {
  title: "ZenCode",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <main>
          <Provider>
            {children}
          </Provider>
        </main>
      </body>
    </html>
  );
}
